# Rustfmt configuration file
# This file configures how rustfmt formats your Rust code

# Set the maximum line width (default is 100)
max_width = 160

# Alternative options you might want to consider:
# max_width = 140  # Even longer lines
# max_width = 80   # Shorter, more traditional width

# Other useful formatting options:
# hard_tabs = false                    # Use spaces instead of tabs
# tab_spaces = 4                       # Number of spaces per tab
# newline_style = "Auto"              # "Auto", "Unix", or "Windows"
# use_small_heuristics = "Default"    # "Default", "Off", "Max"
# reorder_imports = true              # Reorder import statements
# reorder_modules = true              # Reorder module declarations
# remove_nested_parens = true         # Remove unnecessary nested parentheses
# edition = "2021"                    # Rust edition (should match Cargo.toml)
